# Generated by Django 5.1.2 on 2024-12-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customerprofile_driverprofile_delete_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('help_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
