# Generated by Django 5.1.2 on 2024-12-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_booking_date_remove_booking_dropoff_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='license_plate',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='medium',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
