# Generated by Django 5.1.3 on 2024-12-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_vehicle_capacity_remove_vehicle_license_plate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
