# Generated by Django 5.1.3 on 2024-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_carreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreg',
            name='service',
        ),
        migrations.AddField(
            model_name='carreg',
            name='Transportation',
            field=models.BooleanField(default=False),
        ),
    ]
