# Generated by Django 5.1.3 on 2024-12-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_carreg_service_carreg_transportation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carreg',
            options={'verbose_name': 'Car Registration', 'verbose_name_plural': 'Car Registrations'},
        ),
    ]
