# Generated by Django 5.1.2 on 2024-12-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_deal_clicked_by_remove_deal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deal_images/'),
        ),
    ]
