# Generated by Django 5.1.3 on 2024-12-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_carregister_delete_carreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregister',
            name='password',
            field=models.CharField(default='123abc', max_length=255),
        ),
    ]
