# Generated by Django 5.1.3 on 2024-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_carregister_user_alter_carregister_carpic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregister',
            name='carpic',
            field=models.ImageField(blank=True, null=True, upload_to='carpic/'),
        ),
        migrations.AlterField(
            model_name='carregister',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic/'),
        ),
    ]
