# Generated by Django 5.1.3 on 2024-12-23 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_carregister_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phonenumber', models.CharField(default='', max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profilepic/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Driver Registration',
                'verbose_name_plural': 'Car Driver Registrations',
            },
        ),
    ]
