# Generated by Django 5.1.3 on 2025-01-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_booking_customer_prof_booking_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealstatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
